[16.0][IMP] base_wamas_ubl: Add record_to_wamas method
QuocDuong1306/edi pull request #11
Opened 2024-01-10 10:23 UTC by QuocDuong1306

After reviewing, i will :
- Close `partner_export_wamas`, `product_export_wamas`
- Update `allo_edi_partner_export_wamas` and `allo_edi_product_export_wamas`

2024-01-10 10:31 UTC, nilshamerlinck requested changes

2024-01-10 10:31 UTC, nilshamerlinck commented on base_wamas_ubl/models/base_wamas_ubl.py
> +    def record_to_wamas(self, specific_dict, telegram=False):
```suggestion
    def record_to_wamas(self, specific_dict, telegram_type):
```

2024-01-10 10:31 UTC, nilshamerlinck commented on base_wamas_ubl/models/base_wamas_ubl.py
> +            raise ValueError(_("Need telegram for exporting!"))
```suggestion
            raise ValueError(_("Please define telegram_type."))
```

2024-01-10 10:31 UTC, nilshamerlinck commented on base_wamas_ubl/models/base_wamas_ubl.py
> +        if not telegram:
```suggestion
        if not telegram_type:
```

2024-01-10 10:31 UTC, nilshamerlinck commented on base_wamas_ubl/models/base_wamas_ubl.py
> +        return self.dict2wamas(specific_dict, telegram)
```suggestion
        return self.dict2wamas(specific_dict, telegram_type)
```

2024-01-11 01:58 UTC, QuocDuong1306 commented
Thank @nilshamerlinck , I updated

2024-01-11 02:02 UTC, nilshamerlinck approved these changes

2024-02-01 04:16 UTC, closed without merging