[16.0][MIG] edi_sale_oca: Migration to 16.0
QuocDuong1306/edi pull request #7
Opened 2023-09-26 08:38 UTC by QuocDuong1306

2023-09-28 08:02 UTC, nilshamerlinck commented
weird bug in Sale Order form:

![image](https://github.com/QuocDuong1306/edi/assets/511258/8e3c419b-8e81-4c86-ae75-6ebaa58f7874)

2023-09-29 09:07 UTC, nilshamerlinck requested changes

2023-09-29 09:07 UTC, nilshamerlinck commented on edi_sale_oca/tests/test_process.py
> +import mock
```suggestion
from unittest import mock
```

2023-10-02 07:59 UTC, QuocDuong1306 commented on edi_sale_oca/models/sale_order.py
> +        "edi.auto.exchange.consumer.mixin",
This line causes the weird bug in sale order form, do you have any idea?

2024-03-24 12:14 UTC, closed without merging