[16.0][ADD] partner_export_wamas
QuocDuong1306/edi pull request #9
Opened 2023-12-19 04:13 UTC by QuocDuong1306

2023-12-27 03:21 UTC, nilshamerlinck commented on partner_export_wamas/models/res_partner.py
> +        return base_wamas_ubl.export_dict2wamas(dict_partner, telegram)
```suggestion
        return base_wamas_ubl.dict2wamas(dict_partner, telegram)
```

2023-12-27 03:23 UTC, tuantrantg requested changes

2023-12-27 03:23 UTC, tuantrantg commented on partner_export_wamas/models/res_partner.py
> +        return base_wamas_ubl.export_dict2wamas(dict_partner, telegram)
- please replace `export_dict2wamas` by `dict2wamas`
- if there is no `telegram`, please raise warning missing telegram input

2023-12-27 08:21 UTC, QuocDuong1306 commented
Thank @nilshamerlinck @tuantrantg , I updated

2024-01-02 05:49 UTC, nilshamerlinck commented on partner_export_wamas/models/res_partner.py
> +        :rtype: a byte
```suggestion
        :rtype: bytes
```

2024-01-02 05:49 UTC, nilshamerlinck commented on partner_export_wamas/tests/test_export_partner.py
> +# Copyright 2023
see copyrights remark on channel

2024-01-02 07:28 UTC, QuocDuong1306 commented on partner_export_wamas/tests/test_export_partner.py
> +# Copyright 2023
Thank @nilshamerlinck , I updated

2024-03-28 02:59 UTC, closed without merging